url-pretty: "https://msussolutionaccelerators.github.io"
# Name of website
title: Solution Accelerators | Microsoft US

collections:
  accelerators:
    output: true

defaults:
  - scope:
      path: "_accelerators"
    values:
      layout: "accelerator"
  - scope:
      path: "index.html"
    values:
      layout: "default"

exclude:
  - "*.json"
  - "Gemfile*"
  - postcss.config.js
  - tailwind.config.js
  - prettier.config.js
  - README.md
  - "sitemap_atom.xml"
  - "sitemap_rss.xml"
  - "sitemap.xml"
  - "urllist.txt"
  - "robots.txt"
